services:
  mysql_pizzeria:
    image: mysql:8.0
    container_name: mysql-pizzeria
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzeria_db
    ports:
      - "3308:3306"
    volumes:
      - ./sql/pizzeria:/docker-entrypoint-initdb.d
      - mysql_pizzeria_data:/var/lib/mysql

volumes:
  mysql_pizzeria_data:
